[workspace]
members = [
	"moq-transport",
	"moq-relay-ietf",
	"moq-pub",
	"moq-sub",
	"moq-api",
	"moq-clock-ietf",
	"moq-dir",
	"moq-native-ietf",
	"moq-catalog",
]
resolver = "2"

[patch.crates-io]
mp4 = { path = "./third_party/mp4-rust" }

[workspace.dependencies]
web-transport = "0.3"
env_logger = "0.11"
log = { version = "0.4", features = ["std"] }

# Use debug symbols in production until things are more stable
[profile.release]
debug = true
